spring.main.web-application-type=none

spring.datasource.url=jdbc:mysql://root:TofCeCOZooxuVjrVnelvgJnLqxSarRqg@turntable.proxy.rlwy.net:44084/railway
spring.datasource.username=root
spring.datasource.password=TofCeCOZooxuVjrVnelvgJnLqxSarRqg
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

application.title=Apptism